# Generated by Django 5.2.3 on 2025-06-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_stream_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_img',
            field=models.ImageField(blank=True, null=True, upload_to='Category_img/'),
        ),
    ]
